[package]
name = "pombase-chado-json"
version = "38.0.0"
authors = ["Kim Rutherford <kmr44@cam.ac.uk>"]

[lib]
name = "pombase"
path = "src/pombase/lib.rs"

[[test]]
name = "tests"

[dependencies]
serde_derive = "1.0"
serde_json = "1.0"
getopts = "*"
regex = "0.1"
bit-set = "0.4"
chrono = { version = "0.3", features = ["serde"] }
rocket = { git = "https://github.com/SergioBenitez/Rocket", branch = "v0.3" }
rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket", branch = "v0.3" }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket", branch = "v0.3" }
reqwest = "0.7.3"
flate2 = "0.2"
lazy_static = "1.0"

[patch.crates-io]
ring = { git = "https://github.com/SergioBenitez/ring", branch = "v0.11" }

[dependencies.serde]
version = "1.0"
features = ["rc"]

[build-dependencies]
serde_codegen = "0.8"

[dependencies.postgres]
version = "0.14"
features = ["with-serde_json"]

[profile.release]
opt-level = 2
codegen-units = 12

[profile.dev]
opt-level = 0
debug = true
codegen-units = 12
debug-assertions = true
