[package]
name = "pombase-chado-json"
version = "108.0.0"
authors = ["Kim Rutherford <kmr44@cam.ac.uk>"]
edition = "2018"

[lib]
name = "pombase"
path = "src/pombase/lib.rs"

[dependencies]
jemallocator = "0.3.0"
serde_derive = "1.0"
serde_json = "1.0"
getopts = "*"
regex = "1.0"
bit-set = "0.5"
chrono = { version = "0.4", features = ["serde"] }
flate2 = "1.0"
lazy_static = "1.0"
once_cell = "1.2"
uuid = { version = "0.5", features = ["v4", "serde", ] }
bytes = "1.0"
tokio = "^1.6.1"

[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket.git"
version = "0.5.0-rc.1"
features = ["json"]

[dependencies.pombase_rc_string]
git = "https://github.com/pombase/pombase_rc_string.git"
tag = "v0.3.0"
version = "=0.3.0"

[dependencies.serde]
version = "1.0"

[build-dependencies]
serde_codegen = "0.9"

[dependencies.postgres]
version = "0.15"
features = ["with-serde_json", "with-uuid"]

[dependencies.r2d2_postgres]
version = "0.18.0"

[dependencies.r2d2]
version = "0.8.9"

[dependencies.reqwest]
version = "0.11"
features = ["blocking"]

[profile.release]
opt-level = 2
codegen-units = 12

[profile.dev]
opt-level = 0
debug = true
codegen-units = 12
debug-assertions = true
