[package]
name = "pombase-chado-json"
version = "34.0.0"
authors = ["Kim Rutherford <kmr44@cam.ac.uk>"]

[lib]
name = "pombase"
path = "src/pombase/lib.rs"

[[test]]
name = "tests"

[dependencies]
serde_derive = "1.0"
serde_json = "1.0"
getopts = "*"
regex = "0.1"
bit-set = "0.4"
chrono = { version = "0.3", features = ["serde"] }
rocket = "0.3.0"
rocket_codegen = "0.3.0"
rocket_contrib = "0.3.0"

[dependencies.serde]
version = "1.0"
features = ["rc"]

[build-dependencies]
serde_codegen = "0.8"

[dependencies.postgres]
version = "0.14"
features = ["with-serde_json"]

[profile.release]
opt-level = 3
lto = true

[profile.dev]
opt-level = 0
debug = true
codegen-units = 12
debug-assertions = true
