[development]
address = "127.0.0.1"
port = 8400
workers = 1
log = "normal"

[staging]
address = "0.0.0.0"
port = 8500
log = "normal"
workers = 8

[production]
address = "0.0.0.0"
port = 8500
log = "normal"
